### ISSUE TITLE
Does sparsity make some stuff easier?

### ISSUE THREAD

**Issue by Seanny123** [ctn-waterloo/modelling_ideas#28]
The sparsity of our representations is questionable, especially in spa.State. If we increase the sparsity, would the following two things (where _D_ is the number of dimensions) be more easily computable?

![sketch of learning](https://cloud.githubusercontent.com/assets/1918825/10984038/b155db14-83e4-11e5-8a87-a4fa6632ce50.png)

[Link to editable drawing](https://docs.google.com/drawings/d/1WiIDBIuUlz6LsHpuVRu2Vav4oq09LJBHqtGNO1BCVDA/edit?usp=sharing)

In this context, "learning" could be either offline or online.

**Comment by studywolf** [comment]
In general sparsity will help with representing sharper functions

**Comment by Seanny123** [comment]
This is already addressed by Voja, since it lets you learn associative memories, which are super-discontinuous, by increasing encoder sparsity.
