### ISSUE TITLE
Reimplement ANDREA in Nengo

### ISSUE THREAD

**Issue by tcstewar** [ctn-waterloo/modelling_ideas#38]
There's a nice model of affect and decision making that was done in NESim (the Matlab precursor to Nengo).  

http://arts.uwaterloo.ca/~celiasmi/Papers/litt%20eliasmith%20thagard.2008.neural%20affective%20decisions.cogsys.pdf

It's just 5 ensembles, and all 1-D, and gives some nice comparisons to neural data, so it might be a nice clean example to have around.

**Comment by memarsh** [comment]
I'd like to take a look at this!

**Comment by tcstewar** [comment]
> I'd like to take a look at this!

Wonderful!  We should probably meet and chat about it sometime...  :)  I'm still piecing through the paper and figuring out what things are specified in there and what ones we have to guess at....  :)

**Comment by Seanny123** [comment]
Closing because @memarsh totally complete this! Awesome work Mariah!
