### ISSUE TITLE
Convert basal ganglia model to function spaces

### ISSUE THREAD

**Issue by tcstewar** [ctn-waterloo/modelling_ideas#68]
I'm pretty sure we could convert the standard Basal Ganglia model that's in Nengo to use continuous action spaces (by using the function representation stuff).  This would address the nagging worry I've had about it having these perfectly organized groups of neurons, one for each action!

**Comment by studywolf** [comment]
In the same vein as #52?

**Comment by tcstewar** [comment]
Oops!  You're right, this is a duplicate!
