### ISSUE TITLE
Free recall of word list

### ISSUE THREAD

**Issue by Seanny123** [ctn-waterloo/modelling_ideas#82]
In the paper "Memory Retrieval from First Principles" free recall of a list of words is modelled. This seems pretty trivial to with SPA, especially given @xchoo's memory model. But if I recall correctly, no explicit simulation was run?

**Comment by Seanny123** [comment]
@xchoo tells me he included free recall in his Master's thesis, but the encoding mechanism didn't work and he didn't model the retreival/search mechanism. However, this is discussed in his PhD thesis?

**Comment by jgosmann** [comment]
I'm modeling free recall in my PhD thesis.
(Why can't I assign this issue to myself (or anyone else)?)

**Comment by jgosmann** [comment]
The model repo is now public at [ctn-archive/cue-model](https://github.com/ctn-archive/cue-model). A submission to CogSci 2018 has been made and my PhD thesis is in writing. I'd say this issue can be closed? (But I don't have permissions to close it.)
