### ISSUE TITLE
Compare Nengo models to some fun Reservoir models

### ISSUE THREAD

**Issue by tcstewar** [ctn-waterloo/modelling_ideas#9]
Here's a nice reservoir model that does infinite-time memory (i.e. not the fading memory limitation that I'm used to thinking of for reservoirs).

Maass, W. and Joshi, P. and Sontag, E., 'Computational Aspects of Feedback in Neural Circuits', PLOS Computational Biology, 2007, Vol. 3. Nr. 1

http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.0020165

Here's an equivalent Nengo model that's way easier to train:

```python
import nengo
import numpy

model = nengo.Network()
with model:
    state = nengo.Ensemble(n_neurons=300, dimensions=2)
    
    signal_stim_1 = nengo.Node(lambda t: 1 if t%1 < 0.01 else -1)
    signal_stim_2 = nengo.Node(lambda t: 1 if (t+0.5)%1 < 0.01 else -1)
    value_stim = nengo.Node(lambda t: numpy.sin(t*30))
    
    nengo.Connection(signal_stim_1, state[0], transform=100)
    nengo.Connection(signal_stim_2, state[0], transform=-100)
    nengo.Connection(value_stim, state[1])
    
    nengo.Connection(state[0], state[0], synapse=0.1)
   
    result = nengo.Ensemble(n_neurons=50, dimensions=1)
    def calc_result(x):
        if x[0] < 0:
            return x[1]
        else:
            return 0
    nengo.Connection(state, result, function=calc_result)
```

I'm curious how close the comparisons would be to the different examples in that paper.

**Comment by Seanny123** [comment]
Resolved by @arvoelke
